# Generated by Django 5.2.5 on 2025-08-15 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_role_permissions_alter_asset_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='asset',
            name='asset_belongs_to_either_task_or_project',
        ),
    ]
